[package]
name = "basic-rc"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.6"
tokio = { version = "1.43.0", features = ["net"] }
vice-rc = { version = "0.1.0", path = "../../vice-rc" }
