[package]
name = "vice"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.0"
httparse = "1.10.0"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["io-util", "net", "sync", "rt-multi-thread"] }
