[package]
name = "vice"
version = "0.1.0"
edition = "2021"

[dependencies]
httparse = "1.10.0"
httpdate = "1.0.3"
tokio = { version = "1.43.0", features = ["io-util", "net", "rt-multi-thread", "sync"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
