[package]
name = "mvc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tour = { git = "https://github.com/ariaandika/tour.git", version = "0.1.0" }
tsue = { version = "0.1.0", path = "../../tsue" }
