[package]
name = "tsue"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures-util = { version = "0.3.31", default-features = false }
http = "1.2.0"
http-body = "1.0.1"
hyper = "1.6.0"
hyper-util = { version = "0.1.10", features = ["server", "tokio", "http1"], optional = true }
log = { version = "0.4.26", optional = true }
pin-project-lite = "0.2.16"
serde = "1.0.219"
serde_json = "1.0.140"
serde_urlencoded = "0.7.1"
tokio = { version = "1.43.0", features = ["net"], optional = true }

[features]
tokio = ["dep:tokio","dep:hyper-util","hyper/server","hyper/http1"]
log = ["dep:log"]
