[package]
name = "tsue"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.0"
http = "1.2.0"
http-body-util = "0.1.2"
hyper = { version = "1.6.0", features = ["server", "http1"] }
hyper-util = { version = "0.1.10", features = ["server", "tokio", "http1"] }
log = "0.4.26"
pin-project-lite = "0.2.16"
tokio = { version = "1.43.0", features = ["io-util", "net", "rt-multi-thread"] }
