[package]
name = "basic"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
vice = { version = "0.1.0", path = "../../vice" }
